on:
    pull_request: 
    push:
        branches: 
            - main

env:
    NUSHELL_CARGO_PROFILE: ci
    NU_LOG_LEVEL: DEBUG

jobs:
    my-job:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: hustcer/setup-nu@v3.9
              with:
                version: '*'
                check-latest: true
                  # version: "0.80" # Don't use 0.80 here, as it was a float number and will be convert to 0.8, you can use v0.80/0.80.0 or '0.80'
            - run: print $'Nu version info:(char nl)'; version
              shell: nu {0}
            - name: Default shell will be `nu`
              shell: nu {0}
              run: |
                  print $'Nu path:(which nu)(char nl)'
                  def greeting [name: string] {
                      print $'Hello ($name)'
                  }
                  greeting hustcer
