on:
    pull_request: 
    push:
        branches: 
            - main

env:
    NUSHELL_CARGO_PROFILE: ci
    NU_LOG_LEVEL: DEBUG

jobs:
    my-job:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: hustcer/setup-nu@v3.9
              with:
                version: '*'
                check-latest: true
            - name: Check PR
              shell: nu {0}
              run: |
                nu -c "use toolkit.nu *; check pr"
            - name: Run nu-check
              shell: nu {0}
              run: |
                nu ./check-files.nu
